build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
args: {}
labels:
  org.opencontainers.image.title: "Freebox Dashboard"
  org.opencontainers.image.description: "Interface web moderne pour gérer votre Freebox"
  org.opencontainers.image.source: "https://github.com/HgHugo/FreeboxOS-Ultra-Dashboard"
  org.opencontainers.image.licenses: "MIT"
